version: '3.8'
services:
    angular-m1:
        build: 
            context: angular/.
            dockerfile: Dockerfile.m1
        ports:
            - "4201:4200"
        volumes:
        - ./angular/:/usr/src/app
    angular-intel:
        build: 
            context: angular/.
            dockerfile: Dockerfile.intel
        ports:
            - "4202:4200"
        volumes:
            - ./angular/:/usr/src/app

